# Generated by Django 5.0 on 2023-12-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_product_slug_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.IntegerField(default=0),
        ),
    ]
