# Generated by Django 5.0 on 2023-12-16 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_rename_customers_first_n_93c9ec_idx_playground__first_n_e0f9a5_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='playground__first_n_698721_idx',
            old_name='playground__first_n_e0f9a5_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
